### ISSUE TITLE
File path spaces in arguments not escaped

### ISSUE THREAD

**Issue by colinrotherham** [steida/gulp-closure-compiler#15]
Hi,

I've got the following input path with lots of spaces:  
`/Volumes/Sites/Colin Rotherham Design/Personal Projects/CRD.Website/app/public/assets/js/base.min.js`

Which throws the following error:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Command failed: ERROR - Cannot read: /Volumes/Sites/Colin

ERROR - Cannot read: Design/Personal

ERROR - Cannot read: Projects/CRD.Website/app/public/assets/js/base.min.js

ERROR - Cannot read: Rotherham
```

I'm guessing the spaces should have been escaped to:  
`/Volumes/Sites/Colin\ Rotherham\ Design/Personal\ Projects/CRD.Website/app/public/assets/js/base.min.js`

Otherwise the spaces are treated as delimiters, throwing the multiple "Cannot read" errors for each component part.

Thanks

**Comment by steida** [comment]
Good catch. Can you send PR please?

**Comment by colinrotherham** [comment]
No problem, paths as arguments needed to be quoted for safety:
https://github.com/steida/gulp-closure-compiler/pull/16

**Comment by steida** [comment]
Thank you!

**Comment by colinrotherham** [comment]
Some of the other optional flags seem to accept paths which I've not fixed. I'll leave it up to you to decide how to handle these.

**Comment by steida** [comment]
I think is good enough until someone complain.
