### ISSUE TITLE
Support gulp-sourcemaps

### ISSUE THREAD

**Issue by sindresorhus** [steida/gulp-closure-compiler#18]
Most other source map producing plugins supports this. It makes it a lot easier to handle source maps transparently in the pipeline, even between multiple plugins.

https://github.com/floridoo/gulp-sourcemaps#plugin-developers-only-how-to-add-source-map-support-to-plugins

See: https://github.com/sindresorhus/gulp-autoprefixer/blob/fe899ec17ab4a87508821304b8bb5d5b38013643/index.js#L35

And: https://github.com/sindresorhus/gulp-autoprefixer/blob/fe899ec17ab4a87508821304b8bb5d5b38013643/test.js#L27-L91

**Comment by leodido** [comment]
:+1:

**Comment by steida** [comment]
Ok, thank you. I will take a look this weekend. Or someone can send PR.

**Comment by matpimenta** [comment]
I don't know if this helps but by passing the following parameters to closure compiler, it generates the source map files.

compilerFlags: {
...
  create_source_map: 'script.min.js.map',
  output_wrapper: '%output%\n//# sourceMappingURL=' + 'script.min.js.map'
...
}

The only problem is that the "file" and the "sources" in the map are absolute paths pointing to a temporary folder. I think the absolute path could be changed to relative in getFlagFilePath(..) but I'm not sure about the reason behind the files being copied to this temporary folder. Any clues?

**Comment by leodido** [comment]
@matpimenta yes, exactly what I have pointed out in #17

**Comment by steida** [comment]
Fixed.
