### ISSUE TITLE
Compiled file is saved twice

### ISSUE THREAD

**Issue by PavelVanecek** [steida/gulp-closure-compiler#24]
Given example configuration `{fileName: "app.js", dest: "app/build"}` the compiled file is written twice:
1) `__dirname/app/build/app.js` // correct
2) `__dirname/app.js` // incorrect

This issue was introduced in https://github.com/steida/gulp-closure-compiler/commit/da4f2545c80a6b0488288603ddb90b13a58329b7 v0.2.17

Reverting to 0.2.16 fixes it.

The code in question: https://github.com/steida/gulp-closure-compiler/blob/master/index.js#L97
```
args.push('--js_output_file="' + opt.fileName + '"');
```

This code used to be:
```
var outputFilePath = tempWrite.sync('');
args.push('--js_output_file="' + outputFilePath + '"');
```

However it is not and the file is saved twice.

Changing it back to outputFilePath breaks the compilation and most likely breaks sourcemaps too.

**Comment by steida** [comment]
Busy as hell to fix it right now :/

**Comment by alechewitt** [comment]
Yes I am also seeing this same issue.

**Comment by steida** [comment]
PR anyone?

**Comment by freshp86** [comment]
Also seeing the same issue. Is there a workaround? Also any plans to fix?

**Comment by steida** [comment]
Yes I have plan to fix it but zero time to do that next two weeks. If you need it sooner, please fix it and send PR. Thank you.
