### ISSUE TITLE
Usage of TieredCompilation

### ISSUE THREAD

**Issue by zarov** [steida/gulp-closure-compiler#38]
So I understand the advantage of [TieredCompilation](https://github.com/steida/gulp-closure-compiler/blob/master/index.js#L80), but note that if one does not have JDK installed but only JRE, it throws this warning :

> Error: Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.

Shouldn't we be able to add the option to use or not the TieredCompilation (default use it) ? Or else the requirement of JDK needs to be specify in the README (at the end, "Require Java 1.7+" to "Require JDK 1.7+").

What's your opinion on that ?

**Comment by steida** [comment]
Feel free to send PR. Thank you.

**Comment by roydukkey** [comment]
I see this is closed, but was this suggested improvement ever committed? I don't see any documentation.

**Comment by zarov** [comment]
Nope I didn't do anything yet, I kind of forgot it, sorry. Will do whenever I got time, or you can do it if you want.
