### ISSUE TITLE
What's wrong with the pipe?

### ISSUE THREAD

**Issue by Krisa** [steida/gulp-closure-compiler#41]
Somehow, the closure compiler is ignoring the ngAnnotate step I have defined in my pipes:
```javascript
gulp.task('minify-js', () =>
    gulp.src(['public_dev/javascripts/libs/*.js', 'public_dev/javascripts/custom/*.js', 'public_dev/javascripts/custom/controllers/*.js'])
    .pipe(ngAnnotate({
         add: true
    }))
    //.pipe(concat('dist.min.js'))
    .pipe(closureCompiler({
        compilerPath: 'compiler.jar',
        fileName: 'dist.min.js', 
        compilerFlags: {
            language_in: 'ES6',
            language_out: 'ES5'
        },
        continueWithWarnings: true,
        tieredCompilation: true
     }))
    .pipe(gulp.dest('public/javascripts'))
);
```
This is a project using Angular, and it's necessary to annotate (through ngAnnotate) some functions in order for them to be correctly interpreted by Angular once it has been minified. However, this fails and the annotation step is never done. 

To ensure this was not something wrong in my code (like forgetting to annotate a function), I generated the concatenated code with ngAnnotate first without closureCompiler and then I ran closureCompiler in a second step and I could perfectly execute the minified code. 

Any idea what's wrong?

**Comment by zarov** [comment]
Does ngAnnotate concat the files ? Without a specific flag on the compiler, it cannot get all the files in one time, so it only compile one by one, hence the necessary `concat`.

See http://stackoverflow.com/a/4043433/1233787

**Comment by Krisa** [comment]
No ngAnnotate just adds few lines in each file, i.e. doesn't change anything else. I tried to use concat (by uncommenting the line in my example above) but this is not much better, I just end up with an error in ClosureCompiler that "dist.min.js" doesn't exist... this is the exact error:
```
Command failed: java -jar -XX:+TieredCompilation compiler.jar --flagfile="/var/folders/pv/72hgkw1s3wbgq5g9qbdqvgrr0000gp/T/70139e98-8d07-4e84-bb2c-32c782557c45" --language_in=ES6 --language_out=ES5 --js_output_file="dist.min.js"
ERROR - Cannot read: dist.min.js
```

The link you provided is explaining the issue, but it's a cli solution - how could this work in gulp?

**Comment by zarov** [comment]
For now it can't work without a concatenation. If you really don't want the concat, feel free to improve the existing code and do a PR ;)

**Comment by zarov** [comment]
As for your bug with concat, you need to put `dist.min.js` in a directory using `gulp.dest()` (it works for me like that)

**Comment by Krisa** [comment]
I see. So basically 2 tasks, which are chained (`gulp.series`)? The first doing all the operations (like in my case ngAnnotate), then the concat. And then a second gulp task where closure compiler is running?

**Comment by zarov** [comment]
No, you can do it in one task, like that : 
````js
gulp.task('minify-js', () =>
    gulp.src(['public_dev/javascripts/libs/*.js', 'public_dev/javascripts/custom/*.js', 'public_dev/javascripts/custom/controllers/*.js'])
    .pipe(ngAnnotate({
         add: true
    }))
    .pipe(concat('dist.concat.js'))
    .pipe(gulp.dest('tmp'))
    .pipe(closureCompiler({
        compilerPath: 'compiler.jar',
        fileName: 'dist.min.js', 
        compilerFlags: {
            language_in: 'ES6',
            language_out: 'ES5'
        },
        continueWithWarnings: true,
        tieredCompilation: true
     }))
    .pipe(gulp.dest('public/javascripts'))
);
````

**Comment by Krisa** [comment]
Got it, and it works! thank you!

**Comment by zarov** [comment]
No problem ;)
