### ISSUE TITLE
Not continuing with warnings

### ISSUE THREAD

**Issue by e-monson** [steida/gulp-closure-compiler#42]
I have set `continueWithWarnings` to `true` in the closureCompiler options, but compilation still halts for warnings like `WARNING - Suspicious code. The result of the 'not' operator is not being used.` and `WARNING - If this if/for/while really shouldn't have a body, use {}`

**Comment by zarov** [comment]
Hmm I don't think this option is supposed to turn off any warning of Closure Compiler. It is more turning off Java-related and others errors. For turning off specific warning of Closure Compiler, see the related section in the [flags file](https://github.com/steida/gulp-closure-compiler/blob/master/flags.txt#L106-L124).

**Comment by e-monson** [comment]
You're right. I think my issue was caused by something else.

**Comment by zarov** [comment]
No problem, thanks for the feedback !
