### ISSUE TITLE
Successive pipe don't wait for CC to complete.

### ISSUE THREAD

**Issue by roydukkey** [steida/gulp-closure-compiler#44]
``` js
gulp.task('server:js', function () {
	return gulp.src(['./Site/Web/wwwroot/js/test1.js', './Site/Web/wwwroot/js/test2.js'])
		.pipe(sourcemaps.init())
		.pipe(concat('all.min.js', { newLine: ';' }))

		.pipe(closureCompiler({
			compilerPath: './node_modules/google-closure-compiler/compiler.jar',
			fileName: 'all.min.js'
		}))

		.pipe(sourcemaps.write())
		.pipe(gulp.dest('./Site/Web/wwwroot/js'));
});
```

`all.min.js` contains the results from CC, but the sourcemaps aren't included. I believe this is because sourcemaps are written to `all.min.js` before CC has completed compilation. This would be the reason CC logs after the `server:js` task has completed.

```
[13:58:39] Using gulpfile C:\Projects\Mvc6Tests\Gulpfile.js
[13:58:39] Starting 'server:js'...
[13:58:43] Finished 'server:js' after 3.34 s
Process terminated with code 0.
```

Also, if the CC pipe is removed the sourcemaps are written.

**Comment by zarov** [comment]
A better solution if you use CC is to use the builtin source mapping. Add the flag to your options :
````
.pipe(closureCompiler({
    compilerPath: './node_modules/google-closure-compiler/compiler.jar',
    fileName: 'all.min.js',
    compilerFlags: {
        create_source_map: 'all.map'
    }
}))
```` 

Than you'll be sure it is sync with CC, and you don't have another dependency in your project ;)

**Comment by roydukkey** [comment]
I don't think that will work, because then only sourcemap information will be created on the product of `.pipe(concat('all.min.js', { newLine: ';' }))`.

**Comment by zarov** [comment]
You're right indeed ! Well I had a look at it and here's what I found : 
> All plugins between sourcemaps.init() and sourcemaps.write() need to have support for gulp-sourcemaps. [(Source)](https://github.com/floridoo/gulp-sourcemaps#write-inline-source-maps)

I will not do it since I don't really see the point to add another way to generate sourcemaps. But feel free to submit a PR adding the support to sourcemaps !

**Comment by roydukkey** [comment]
I would like to try. From looking at the list of js supported plugins for gulp-sourcemaps, it seems there others that could potentially be used in conjunction with gulp-closure-compiler, just like I'm trying to do with gulp-concat.

Here is a question I have though. Is this line being used? I don't see it referenced anywhere. What is its purpose?

https://github.com/steida/gulp-closure-compiler/blob/e41c6e9c34b67ab7a4e1b206e0e6fdbe3971e24c/index.js#L74

**Comment by zarov** [comment]
Cool, thank you !

This line was for setting the path of the output file, but it changed since, so you can remove it, no problem should appear from it.

**Comment by roydukkey** [comment]
Just so that it is known, I will not be putting anymore effort into this. It has been implemented already through http://www.github.com/chadkillingsworth/closure-compiler-npm

**Comment by zarov** [comment]
No problem. Did you move to this plugin ?

**Comment by roydukkey** [comment]
I probably will as it is the official implementation. The code looks to be clearer and more concise as well.
