### ISSUE TITLE
Leaking temporary --flagfile

### ISSUE THREAD

**Issue by roydukkey** [steida/gulp-closure-compiler#45]
The flagfile that is being create by `getFlagFilePath()` isn't being deleted after completion. This isn't breaking anything, but it should be clean up after our process has completed.

**Comment by zarov** [comment]
It's creating a tmp file in the tmp section of the user computer, so I don't know if we need to delete it ourself ?

**Comment by roydukkey** [comment]
I know, but seeing as we don't reuse them and with the use of watching services (ie. BrowserSync), the amount of files will quickly grow into the hundreds. I actually had more than 1000 temp files specifically from gulp-closure-compliler.

**Comment by zarov** [comment]
Yes, totally. I don't know about the temp-write module, if you know what to do, add it in your work on source maps please ;)
