### ISSUE TITLE
Multiple file outputs

### ISSUE THREAD

**Issue by b-strauss** [steida/gulp-closure-compiler#50]
Hi, my build task currently looks like this.

```javascript
gulp.task('minify-js', function () {
  return gulp.src('./js/**/*.js')
             .pipe(closureCompiler('build.js'))
             .pipe(gulp.dest('./modules'));
});
```

It currently compiles everything into one file. I don't want that. What I want is to compile to a single file per input file while keeping the folder structure.

This:
```
./js
    /core
        core.js (original)
        test.js (original)
```

should become this:
```
./modules
    /core
        core.js (minified)
        test.js (minified)
```

Is that possible? Is there some other gulp package that can do that?

**Comment by zarov** [comment]
Hello, sorry for the delay. No, it is not possible to to do that. If you want to compile file by file, you can maybe use [gulp-foreach](https://www.npmjs.com/package/gulp-foreach).

**Comment by b-strauss** [comment]
Hi, yes gulp-foreach works out. :+1:
