### ISSUE TITLE
How can I bundle the angular.js framework into the Closure output?

### ISSUE THREAD

**Issue by gurmukhp** [steida/gulp-closure-compiler#52]
Is it possible to add the angular js framework to the output of the compiler?

I've tried adding it as a source like so:

```
  return gulp.src([
        './dev/**/*.js', 'node_modules/google-closure-library/closure/goog/base.js', 'node_modules/angular/angular.min.js'])
```

However the compiled output doesn't contain the angular framework. I need to manually include it on the HTML page.

Aside from concatenating the closure output to the angular.js file, is there another way?

Thanks

**Comment by zarov** [comment]
You should use the a specific compiler flag, setting Angular as an extern : 
````js
return gulp.src(['./dev/**/*.js'])
    .pipe(closureCompiler({
      compilerPath: 'bower_components/closure-compiler/compiler.jar',
      fileName: 'build.js',
      compilerFlags: {
         externs: './path/to/angular.extern.js'
      }
    }))
````

See https://github.com/google/closure-compiler/wiki/Externs-For-Common-Libraries#angular

**Comment by gurmukhp** [comment]
Hi Zarov,

Sorry I should've added my gulp config. I tried the externs approach, this ensures that the compiler doesn't complain about undeclared variables but doesn't actually prepend the library into the code:

```
gulp.task('jscompile-prod', function() {
  return gulp.src([
        './dev/**/*.js', 'node_modules/google-closure-library/closure/goog/base.js'])
      .pipe(cc({
        compilerPath: 'node_modules/google-closure-compiler/compiler.jar',
        fileName: 'app.min.js',
        compilerFlags: {
          externs: [
            'node_modules/google-closure-compiler/contrib/externs/angular-1.4.js',
            'node_modules/google-closure-compiler/contrib/externs/angular-1.4-http-promise_templated.js',
            'node_modules/google-closure-compiler/contrib/externs/angular-1.4-mocks.js',
            'node_modules/google-closure-compiler/contrib/externs/angular-1.4-q_templated.js'
          ],
          closure_entry_point: 'app.module',
          compilation_level: 'ADVANCED_OPTIMIZATIONS',
          only_closure_dependencies: true,
          export_local_property_definitions: true,
          warning_level: 'VERBOSE',
          export_local_property_definitions: true,
          angular_pass: true,
          generate_exports: true,
          output_wrapper: '(function(){%output%}).call(window);',
        }
      }))
      .on('error', notify.onError({
        title: 'Compiler Error',
        message: '<%= error.message %>'
      }))
      .pipe(gulp.dest('public/static/'))
      .pipe(notify({
        title: 'Prod JS Compiled',
        message: 'Prod JS Compiled'
      }));
});
```

app.min.js doesn't include any of the angular library.

**Comment by zarov** [comment]
Oh sorry I didn't understand it like that. It is not possible to prepend the library in your code, I think the best way to do it is to concatenate it after your compilation. Also when using libraries like Angular, I think (it's my opinion) it's best to separate it from your main file, except if you have a requirement for including everything in one single file.

**Comment by gurmukhp** [comment]
Until our server supports HTTP2, I think it's more performant to make one request as opposed to many. 

I'll create a concatenate command which'll add the Angular library.

Thanks once again!
