### ISSUE TITLE
process_jquery_primitives flag always throws an error

### ISSUE THREAD

**Issue by kmcaloon** [steida/gulp-closure-compiler#58]
I'm not sure if this is a bug or if I am missing something, but any time I set process_jquery_primitives to true under compilerFlags I always receive the following error:

The jQuery pass and the Closure pass cannot both be enabled.

It looks like to matter what configurations I try to set this always throws the same error.

**Comment by zarov** [comment]
Hi, this is an issue from the Compiler itself, not from this plugin. See https://github.com/google/closure-compiler/commit/cf880aecdf94222367f20ffe807b0f343d967546

It seems that the solution here is to also add the `process_closure_primitives` flag to false.
