### ISSUE TITLE
angular.$http expressions are not callable

### ISSUE THREAD

**Issue by zteBill** [steida/gulp-closure-compiler#59]
gulp-google-closure-compiler: /src/app/frontend/uploadimage/controller.js:98: ERROR - angular.$http expressions are not callable
          $http({
1 error(s), 0 warning(s), 94.7% typed
why not support  ANGULARJS object $http  
thanks! @steida

**Comment by zarov** [comment]
Hi, that's not an issue with this plugin, please refer to the main project to find a fix to your error.

https://github.com/google/closure-compiler
